# Generated by Django 4.1.3 on 2022-11-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nivel',
        ),
    ]
