# Generated by Django 4.1.3 on 2022-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_enrollment', '0002_remove_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1),
        ),
    ]
