# Generated by Django 4.1.3 on 2022-11-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_enrollment', '0003_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tempo_duracao',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
