# Generated by Django 4.1.3 on 2022-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_enrollment', '0004_curso_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_do_aluno',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
